sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
install: npm install
script: npm run validate
after_success:
  - npm install -g semantic-release@15
  - semantic-release pre && npm publish && semantic-release post
branches:
  only: master
